# List of 100 popular manga volumes for testing
TEST_MANGA = [
    ("One Piece", 1),
    ("One Piece", 2),
    ("One Piece", 3),
    ("Naruto", 1),
    ("Naruto", 2),
    ("Naruto", 3),
    ("Bleach", 1),
    ("Bleach", 2),
    ("Bleach", 3),
    ("Dragon Ball", 1),
    ("Dragon Ball", 2),
    ("Dragon Ball", 3),
    ("Death Note", 1),
    ("Death Note", 2),
    ("Attack on Titan", 1),
    ("Attack on Titan", 2),
    ("Attack on Titan", 3),
    ("Fullmetal Alchemist", 1),
    ("Fullmetal Alchemist", 2),
    ("My Hero Academia", 1),
    ("My Hero Academia", 2),
    ("My Hero Academia", 3),
    ("Demon Slayer", 1),
    ("Demon Slayer", 2),
    ("Tokyo Ghoul", 1),
    ("Tokyo Ghoul", 2),
    ("One Punch Man", 1),
    ("One Punch Man", 2),
    ("Hunter x Hunter", 1),
    ("Hunter x Hunter", 2),
    ("JoJo's Bizarre Adventure", 1),
    ("JoJo's Bizarre Adventure", 2),
    ("Fairy Tail", 1),
    ("Fairy Tail", 2),
    ("Sword Art Online", 1),
    ("Sword Art Online", 2),
    ("Black Clover", 1),
    ("Black Clover", 2),
    ("The Promised Neverland", 1),
    ("The Promised Neverland", 2),
    ("Spy x Family", 1),
    ("Spy x Family", 2),
    ("Jujutsu Kaisen", 1),
    ("Jujutsu Kaisen", 2),
    ("Chainsaw Man", 1),
    ("Chainsaw Man", 2),
    ("Vinland Saga", 1),
    ("Vinland Saga", 2),
    ("Berserk", 1),
    ("Berserk", 2),
    ("Monster", 1),
    ("Monster", 2),
    ("Vagabond", 1),
    ("Vagabond", 2),
    ("20th Century Boys", 1),
    ("20th Century Boys", 2),
    ("Naoki Urasawa's Monster", 1),  # Duplicate, but different
    ("Steins;Gate", 1),
    ("Steins;Gate", 2),
    ("Psycho-Pass", 1),
    ("Psycho-Pass", 2),
    ("Ergo Proxy", 1),
    ("Ergo Proxy", 2),
    ("Serial Experiments Lain", 1),
    ("Welcome to the N.H.K.", 1),
    ("Welcome to the N.H.K.", 2),
    ("Boogiepop and Others", 1),
    ("Paprika", 1),
    ("Paprika", 2),
    ("Perfect Blue", 1),
    ("Akira", 1),
    ("Akira", 2),
    ("Ghost in the Shell", 1),
    ("Ghost in the Shell", 2),
    ("Battle Angel Alita", 1),
    ("Battle Angel Alita", 2),
    ("Neon Genesis Evangelion", 1),
    ("Neon Genesis Evangelion", 2),
    ("Cowboy Bebop", 1),
    ("Trigun", 1),
    ("Trigun", 2),
    ("Outlaw Star", 1),
    ("Samurai Champloo", 1),
    ("Wicked City", 1),
    ("Urotsukidoji", 1),
    ("La Blue Girl", 1),
    ("Discipline", 1),
    ("Night Shift Nurses", 1),
    ("Bible Black", 1),
    ("La Blue Girl", 2),
    ("Discipline", 2),
    ("Night Shift Nurses", 2),
    ("Bible Black", 2),
    ("Euphoria", 1),
    ("Euphoria", 2),
    ("Shoujo Ramune", 1),
    ("Shoujo Ramune", 2),
    ("Resort Boin", 1),
    ("Resort Boin", 2),
    ("Oni Chichi", 1),
    ("Oni Chichi", 2),
    ("Imouto Paradise", 1),
    ("Imouto Paradise", 2),
    ("Oni Chichi", 3),
    ("Imouto Paradise", 3),
    ("Euphoria", 3),
    ("Shoujo Ramune", 3),
    ("Resort Boin", 3),
    ("Bible Black", 3),
    ("La Blue Girl", 3),
    ("Discipline", 3),
    ("Night Shift Nurses", 3),
]
