# Streamlit Secrets Configuration
# Add your API keys here for local development
# For production deployment, add these to Streamlit Cloud secrets

# DeepSeek API Key for manga data lookup
DEEPSEEK_API_KEY = "your_deepseek_api_key_here"

# Google Books API Key for cover images
GOOGLE_BOOKS_API_KEY = "your_google_books_api_key_here"

