# Streamlit Secrets Configuration
# Add your DeepSeek API key here for local development
# For production deployment, add this to Streamlit Cloud secrets

DEEPSEEK_API_KEY = "your_deepseek_api_key_here"

